// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package store

import ()

type SecretCache struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	ImageUrl string `json:"image_url"`
}
